services:
  - type: web
    name: koseki
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
    envVars:
      - key: APP_ENV
        value: production