services:
  - type: web
    name: laravel-docker-app
    env: docker
    plan: free
    buildCommand: |
      cp .env.example .env
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d0vusfqli9vc73d9qd40-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: kosekidb
      - key: DB_USERNAME
        value: kosekidb_user
      - key: DB_PASSWORD
        value: i8YbLm3jVmqy994G7RvQaO2Uitme82d6